### ISSUE TITLE
Throttle issue with "1.0"

### ISSUE THREAD

**Issue by swirlingsand** [udacity/CarND-Behavioral-Cloning-P3#10]
Some folks in slack reported having trouble with default 1.0 throttle. Suggest reviewing or at least changing the default stetting to something else like ".9"

![image](https://cloud.githubusercontent.com/assets/18080164/22860502/628decd4-f0c5-11e6-852c-77b2d28b77e9.png)

**Comment by awbrown90** [comment]
Thanks for the feedback and currently looking into why the car gets stuck not wanting to go forward sometimes. Debugging now, I did discover that if the brake key is pressed 's' or 'down arrow' it should start driving again.

**Comment by awbrown90** [comment]
Updated drive.py with a very nice PI controller from @joshchao39  that seems to address any throttle lock up issues. Please test with new drive.py updates and if problems still occur reopen the case.
