### ISSUE TITLE
import socketio 

### ISSUE THREAD

**Issue by kargarisaac** [udacity/CarND-Behavioral-Cloning-P3#17]
I can not import socketio in drive.py . I installed it but it gives me "no module named socketio" error.
how can I solve the problem?

**Comment by lelordoftech** [comment]
@kargarisaac, you can try to install "flask-socketio" instead of "socketio"

**Comment by ashaik4** [comment]
@kargarisaac one more option is to simply use the udacity term1 starter kit from [https://github.com/udacity/CarND-Term1-Starter-Kit](url) and install the environment.yml.

**Comment by mvirgo** [comment]
Looks like this is solved; also, `flask-socketio` is part of the starter kit as mentioned by ashaik4, which is listed as a dependency for this project.
