### ISSUE TITLE
Paths in example data file don't match when generating your own.

### ISSUE THREAD

**Issue by frankcarey** [udacity/CarND-Behavioral-Cloning-P3#19]
The example file has `IMG/center_2017_05_21_19_15_37_960.jpg`, but when the recorder is generating files, it has the full path `/home/[stuff]/CarND-Behavioral-Cloning-P3/data/train_3/`.. combine this with the fact that `image = cv2.imread(img_path)` silently fails on missing files (Returning a null) and this can cause some headaches. Please just make them all relative to the csv file.

**Comment by mvirgo** [comment]
Looks like we've since changed this example to be different than what caused the issue, so closing this one out.
