### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by danieledema** [udacity/CarND-Behavioral-Cloning-P3#22]
Hello,
I faced an issue when running drive.py to autonomously drive the car.
In practice, the steering and throttle data sent to the simulator contained the dot "." character instead of the comma ",".
This caused strange behaviours, but no errors.

To fix this I just added a "replace" call on the strings before sending them to the simulator, but I do not know if this can be the final solution.

I thought it could be caused by the locale settings because I live in Italy and have my PC set with italian locale.

I hope this post can be of any help.
Daniele

**Comment by mvirgo** [comment]
Thanks for noting! This is also referenced in the ReadMe as added in a previous commit, 882ce3c3d34b73ec9b5a9d6b333eca7fbc21f544.
