### ISSUE TITLE
wrong codes in model.fit_generator() ?

### ISSUE THREAD

**Issue by HenryHXYao** [udacity/CarND-Behavioral-Cloning-P3#38]
In the project: behavioral cloning, the last three lines in the sample codes in 18.Generators 
(https://classroom.udacity.com/nanodegrees/nd013/parts/edf28735-efc1-4b99-8fbb-ba9c432239c8/modules/6b6c37bc-13a5-47c7-88ed-eb1fce9789a0/lessons/3fc8dd70-23b3-4f49-86eb-a8707f71f8dd/concepts/b602658e-8a68-44e5-9f0b-dfa746a0cc1a) are:

model.fit_generator(train_generator, steps_per_epoch= len(train_samples), validation_data=validation_generator, validation_steps=len(validation_samples), epochs=5, verbose = 1)

However, I checked the keras documentation:
(https://keras.io/models/sequential/)

steps_per_epoch: Integer. Total number of steps (batches of samples) to yield from generatorbefore declaring one epoch finished and starting the next epoch. It should typically be equal to ceil(num_samples / batch_size) Optional for Sequence: if unspecified, will use the len(generator) as a number of steps.

validation_steps: Only relevant if validation_data is a generator. Total number of steps (batches of samples) to yield from validation_data generator before stopping at the end of every epoch. It should typically be equal to the number of samples of your validation dataset divided by the batch size. Optional for Sequence: if unspecified, will use the len(validation_data) as a number of steps.

So the steps_per_epoch and  validation_steps should be 

steps_per_epoch= ceil(len(train_samples)/batch_size)

validation_steps= ceil(len(validation_samples)/batch_size)

?

**Comment by mvirgo** [comment]
Thanks for noting! I think this is likely under the previous Keras style (pre V2) that used `samples_per_epoch` instead of `steps_per_epoch`, so that means we need to correct this to the updated syntax.

(The old version you did want to provide the full length of your training samples, while now you want to divide by batch size, as each "step" is a batch's worth of samples).

I'll update here when it is fixed!

**Comment by mvirgo** [comment]
This has been updated now (note that it may not immediately update within your own classroom). Thanks again for noting our use of the old Keras syntax here!

**Comment by HenryHXYao** [comment]
many thx for this fix !
